<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>

<div class="banner" style="margin:0;"><img src="${ctx}/resources/web/image/wsbs.jpg" /></div>
<div class="tab bstab">
    <ul class="tab_menu">
        <li class="current">个人办事</li>
        <li>网上办事</li>
        <li>部门服务</li>
    </ul>
    <div class="tab_content">
        <ul>
<li><a href="http://www.pnbs.gov.cn/web!listItem.action?ivo.showtype=gr&ivo.typeimg=/sp/out/images/itemtypeimg/gr/ztfl/root_gr_ztfl_sysy.png&ivo.showtypename=%C9%FA%D3%FD%CA%D5%D1%F8&ivo.affairid=WORDBOOK00051581" target="_blank"><img src="${ctx}/resources/web/image/icons/1.png" width="64" height="64" /><br />生育收养</a></li>
<li><a href="http://www.pnbs.gov.cn/web!listItem.action?ivo.showtype=gr&ivo.typeimg=/sp/out/images/itemtypeimg/gr/ztfl/root_gr_ztfl_hj.png&ivo.showtypename=%BB%A7%BC%AE&ivo.affairid=WORDBOOK00051582" target="_blank"><img src="${ctx}/resources/web/image/icons/2.png" width="64" height="64" /><br />户籍</a></li>
<li><a href="http://www.pnbs.gov.cn/web!listItem.action?ivo.showtype=gr&ivo.typeimg=/sp/out/images/itemtypeimg/gr/ztfl/root_gr_ztfl_jiaoyu.png&ivo.showtypename=%BD%CC%D3%FD&ivo.affairid=WORDBOOK00051583" target="_blank"><img src="${ctx}/resources/web/image/icons/3.png" width="64" height="64" /><br />教育</a></li>
<li><a href="http://www.pnbs.gov.cn/web!listItem.action?ivo.showtype=gr&ivo.typeimg=/sp/out/images/itemtypeimg/gr/ztfl/root_gr_ztfl_whty.png&ivo.showtypename=%CE%C4%BB%AF%CC%E5%D3%FD&ivo.affairid=WORDBOOK00051598" target="_blank"><img src="${ctx}/resources/web/image/icons/4.png" width="64" height="64" /><br />文化体育</a></li>
<li><a href="http://www.pnbs.gov.cn/web!listItem.action?ivo.showtype=gr&ivo.typeimg=/sp/out/images/itemtypeimg/gr/ztfl/root_gr_ztfl_zf.png&ivo.showtypename=%D7%A1%B7%BF&ivo.affairid=WORDBOOK00051592" target="_blank"><img src="${ctx}/resources/web/image/icons/5.png" width="64" height="64" /><br />住房</a></li>
<li><a href="http://www.pnbs.gov.cn/web!listItem.action?ivo.showtype=gr&ivo.typeimg=/sp/out/images/itemtypeimg/gr/ztfl/root_gr_ztfl_by.png&ivo.showtypename=%B1%F8%D2%DB&ivo.affairid=WORDBOOK00051584" target="_blank"><img src="${ctx}/resources/web/image/icons/6.png" width="64" height="64" /><br />兵役</a></li>
<li><a href="http://www.pnbs.gov.cn/web!listItem.action?ivo.showtype=gr&ivo.typeimg=/sp/out/images/itemtypeimg/gr/ztfl/root_gr_ztfl_juye.png&ivo.showtypename=%BE%CD%D2%B5&ivo.affairid=WORDBOOK00051585" target="_blank"><img src="${ctx}/resources/web/image/icons/7.png" width="64" height="64" /><br />就业</a></li>
<li><a href="http://www.pnbs.gov.cn/web!listItem.action?ivo.showtype=gr&ivo.typeimg=/sp/out/images/itemtypeimg/gr/ztfl/root_gr_ztfl_ns.png&ivo.showtypename=%C4%C9%CB%B0&ivo.affairid=WORDBOOK00051586" target="_blank"><img src="${ctx}/resources/web/image/icons/8.png" width="64" height="64" /><br />纳税</a></li>
<li><a href="http://www.pnbs.gov.cn/web!listItem.action?ivo.showtype=gr&ivo.typeimg=/sp/out/images/itemtypeimg/gr/ztfl/root_gr_ztfl_sb.png&ivo.showtypename=%C9%E7%B1%A3&ivo.affairid=WORDBOOK00051587" target="_blank"><img src="${ctx}/resources/web/image/icons/9.png" width="64" height="64" /><br />社保</a></li>
<li><a href="http://www.pnbs.gov.cn/web!listItem.action?ivo.showtype=gr&ivo.typeimg=/sp/out/images/itemtypeimg/gr/ztfl/root_gr_ztfl_hy.png&ivo.showtypename=%BB%E9%D2%F6&ivo.affairid=WORDBOOK00051588" target="_blank"><img src="${ctx}/resources/web/image/icons/10.png" width="64" height="64" /><br />婚姻</a></li>
<li><a href="http://www.pnbs.gov.cn/web!listItem.action?ivo.showtype=gr&ivo.typeimg=/sp/out/images/itemtypeimg/gr/ztfl/root_gr_ztfl_yl.png&ivo.showtypename=%D2%BD%C1%C6&ivo.affairid=WORDBOOK00051589" target="_blank"><img src="${ctx}/resources/web/image/icons/11.png" width="64" height="64" /><br />医疗</a></li>
<li><a href="http://www.pnbs.gov.cn/web!listItem.action?ivo.showtype=gr&ivo.typeimg=/sp/out/images/itemtypeimg/gr/ztfl/root_gr_ztfl_crj.png&ivo.showtypename=%B3%F6%C8%EB%BE%B3&ivo.affairid=WORDBOOK00051590" target="_blank"><img src="${ctx}/resources/web/image/icons/12.png" width="64" height="64" /><br />出入境</a></li>
<li><a href="http://www.pnbs.gov.cn/web!listItem.action?ivo.showtype=gr&ivo.typeimg=/sp/out/images/itemtypeimg/gr/ztfl/root_gr_ztfl_shjz.png&ivo.showtypename=%C9%E7%BB%E1%BE%C8%D6%FA&ivo.affairid=WORDBOOK00051591" target="_blank"><img src="${ctx}/resources/web/image/icons/13.png" width="64" height="64" /><br />社会救助</a></li>
<li><a href="http://www.pnbs.gov.cn/web!listItem.action?ivo.showtype=gr&ivo.typeimg=/sp/out/images/itemtypeimg/gr/ztfl/root_gr_ztfl_sfgz.png&ivo.showtypename=%CB%BE%B7%A8%B9%AB%D6%A4&ivo.affairid=WORDBOOK00051593" target="_blank"><img src="${ctx}/resources/web/image/icons/14.png" width="64" height="64" /><br />司法公证</a></li>
<li><a href="http://www.pnbs.gov.cn/web!listItem.action?ivo.showtype=gr&ivo.typeimg=/sp/out/images/itemtypeimg/gr/ztfl/root_gr_ztfl_swbz.png&ivo.showtypename=%CB%C0%CD%F6%E9%EB%D4%E1&ivo.affairid=WORDBOOK00051594" target="_blank"><img src="${ctx}/resources/web/image/icons/15.png" width="64" height="64" /><br />死亡殡葬</a></li>
<li><a href="http://www.pnbs.gov.cn/web!listItem.action?ivo.showtype=gr&ivo.typeimg=/sp/out/images/itemtypeimg/gr/ztfl/root_gr_ztfl_zyzg.png&ivo.showtypename=%D6%B0%D2%B5%D7%CA%B8%F1&ivo.affairid=WORDBOOK00051595" target="_blank"><img src="${ctx}/resources/web/image/icons/16.png" width="64" height="64" /><br />职业资格</a></li>
<li><a href="http://www.pnbs.gov.cn/web!listItem.action?ivo.showtype=gr&ivo.typeimg=/sp/out/images/itemtypeimg/gr/ztfl/root_gr_ztfl_xfwq.png&ivo.showtypename=%CF%FB%B7%D1%CE%AC%C8%A8&ivo.affairid=WORDBOOK00051596" target="_blank"><img src="${ctx}/resources/web/image/icons/17.png" width="64" height="64" /><br />消费维权</a></li>
<li><a href="http://www.pnbs.gov.cn/web!listItem.action?ivo.showtype=gr&ivo.typeimg=/sp/out/images/itemtypeimg/gr/ztfl/root_gr_ztfl_jt.png&ivo.showtypename=%BD%BB%CD%A8&ivo.affairid=WORDBOOK00051597" target="_blank"><img src="${ctx}/resources/web/image/icons/18.png" width="64" height="64" /><br />交通</a></li>
<li><a href="http://www.pnbs.gov.cn/web!listItem.action?ivo.showtype=gr&ivo.typeimg=/sp/out/images/itemtypeimg/gr/ztfl/root_gr_ztfl_zscq.png&ivo.showtypename=%D6%AA%CA%B6%B2%FA%C8%A8&ivo.affairid=WORDBOOK00051599" target="_blank"><img src="${ctx}/resources/web/image/icons/19.png" width="64" height="64" /><br />知识产权</a></li>
<li><a href="http://www.pnbs.gov.cn/web!listItem.action?ivo.showtype=gr&ivo.typeimg=/sp/out/images/itemtypeimg/gr/ztfl/root_gr_ztfl_mzzj.png&ivo.showtypename=%C3%F1%D7%E5%D7%DA%BD%CC&ivo.affairid=WORDBOOK00051600" target="_blank"><img src="${ctx}/resources/web/image/icons/20.png" width="64" height="64" /><br />民族宗教</a></li>
<li><a href="http://www.pnbs.gov.cn/web!listItem.action?ivo.showtype=gr&ivo.typeimg=/sp/out/images/itemtypeimg/gr/ztfl/root_gr_ztfl_qt.png&ivo.showtypename=%C6%E4%CB%FB&ivo.affairid=WORDBOOK00051601" target="_blank"><img src="${ctx}/resources/web/image/icons/21.png" width="64" height="64" /><br />其它</a></li>
        </ul>       
        <ul class="hide">
<li><a href="http://www.pnbs.gov.cn/web!listItem.action?ivo.showtype=qy&ivo.typeimg=/sp/out/images/itemtypeimg/qy/ztfl/root_qy_ztfl_slbg.png&ivo.showtypename=%C9%E8%C1%A2%B1%E4%B8%FC&ivo.affairid=WORDBOOK00051620" target="_blank"><img src="${ctx}/resources/web/image/icons/22.png" width="64" height="64" /><br />设立变更</a></li>
<li><a href="http://www.pnbs.gov.cn/web!listItem.action?ivo.showtype=qy&ivo.typeimg=/sp/out/images/itemtypeimg/qy/ztfl/root_qy_ztfl_njns.png&ivo.showtypename=%C4%EA%BC%EC%C4%EA%C9%F3&ivo.affairid=WORDBOOK00051621" target="_blank"><img src="${ctx}/resources/web/image/icons/23.png" width="64" height="64" /><br />年检年审</a></li>
<li><a href="http://www.pnbs.gov.cn/web!listItem.action?ivo.showtype=qy&ivo.typeimg=/sp/out/images/itemtypeimg/qy/ztfl/root_qy_ztfl_cwsw.png&ivo.showtypename=%B2%C6%CE%F1%CB%B0%CE%F1&ivo.affairid=WORDBOOK00051622" target="_blank"><img src="${ctx}/resources/web/image/icons/24.png" width="64" height="64" /><br />财务税务</a></li>
<li><a href="http://www.pnbs.gov.cn/web!listItem.action?ivo.showtype=qy&ivo.typeimg=/sp/out/images/itemtypeimg/qy/ztfl/root_qy_ztfl_zyzb.png&ivo.showtypename=%D7%BC%D3%AA%D7%BC%B0%EC&ivo.affairid=WORDBOOK00051623" target="_blank"><img src="${ctx}/resources/web/image/icons/25.png" width="64" height="64" /><br />准营准办</a></li>
<li><a href="http://www.pnbs.gov.cn/web!listItem.action?ivo.showtype=qy&ivo.typeimg=/sp/out/images/itemtypeimg/qy/ztfl/root_qy_ztfl_lxsp.png&ivo.showtypename=%C1%A2%CF%EE%C9%F3%C5%FA&ivo.affairid=WORDBOOK00051624" target="_blank"><img src="${ctx}/resources/web/image/icons/26.png" width="64" height="64" /><br />立项审批</a></li>
<li><a href="http://www.pnbs.gov.cn/web!listItem.action?ivo.showtype=qy&ivo.typeimg=/sp/out/images/itemtypeimg/qy/ztfl/root_qy_ztfl_zzrz.png&ivo.showtypename=%D7%CA%D6%CA%C8%CF%D6%A4&ivo.affairid=WORDBOOK00051625" target="_blank"><img src="${ctx}/resources/web/image/icons/27.png" width="64" height="64" /><br />资质认证</a></li>
<li><a href="http://www.pnbs.gov.cn/web!listItem.action?ivo.showtype=qy&ivo.typeimg=/sp/out/images/itemtypeimg/qy/ztfl/root_qy_ztfl_jrtz.png&ivo.showtypename=%BD%F0%C8%DA%CD%B6%D7%CA&ivo.affairid=WORDBOOK00051626" target="_blank"><img src="${ctx}/resources/web/image/icons/28.png" width="64" height="64" /><br />金融投资</a></li>
<li><a href="http://www.pnbs.gov.cn/web!listItem.action?ivo.showtype=qy&ivo.typeimg=/sp/out/images/itemtypeimg/qy/ztfl/root_qy_ztfl_dwjl.png&ivo.showtypename=%B6%D4%CD%E2%BD%BB%C1%F7&ivo.affairid=WORDBOOK00051627" target="_blank"><img src="${ctx}/resources/web/image/icons/29.png" width="64" height="64" /><br />对外交流</a></li>
<li><a href="http://www.pnbs.gov.cn/web!listItem.action?ivo.showtype=qy&ivo.typeimg=/sp/out/images/itemtypeimg/qy/ztfl/root_qy_ztfl_sfgz.png&ivo.showtypename=%CB%BE%B7%A8%B9%AB%D6%A4&ivo.affairid=WORDBOOK00051628" target="_blank"><img src="${ctx}/resources/web/image/icons/30.png" width="64" height="64" /><br />司法公证</a></li>
<li><a href="http://www.pnbs.gov.cn/web!listItem.action?ivo.showtype=qy&ivo.typeimg=/sp/out/images/itemtypeimg/qy/ztfl/root_qy_ztfl_jsgl.png&ivo.showtypename=%BD%A8%C9%E8%B9%DC%C0%ED&ivo.affairid=WORDBOOK00051629" target="_blank"><img src="${ctx}/resources/web/image/icons/31.png" width="64" height="64" /><br />建设管理</a></li>
<li><a href="http://www.pnbs.gov.cn/web!listItem.action?ivo.showtype=qy&ivo.typeimg=/sp/out/images/itemtypeimg/qy/ztfl/root_qy_ztfl_ldbz.png&ivo.showtypename=%C0%CD%B6%AF%B1%A3%D5%CF&ivo.affairid=WORDBOOK00051630" target="_blank"><img src="${ctx}/resources/web/image/icons/32.png" width="64" height="64" /><br />劳动保障</a></li>
<li><a href="http://www.pnbs.gov.cn/web!listItem.action?ivo.showtype=qy&ivo.typeimg=/sp/out/images/itemtypeimg/qy/ztfl/root_qy_ztfl_rlzy.png&ivo.showtypename=%C8%CB%C1%A6%D7%CA%D4%B4&ivo.affairid=WORDBOOK00051631" target="_blank"><img src="${ctx}/resources/web/image/icons/33.png" width="64" height="64" /><br />人力资源</a></li>
<li><a href="http://www.pnbs.gov.cn/web!listItem.action?ivo.showtype=qy&ivo.typeimg=/sp/out/images/itemtypeimg/qy/ztfl/root_qy_ztfl_zljc.png&ivo.showtypename=%D6%CA%C1%BF%BC%EC%B2%E9&ivo.affairid=WORDBOOK00051632" target="_blank"><img src="${ctx}/resources/web/image/icons/34.png" width="64" height="64" /><br />质量检查</a></li>
<li><a href="http://www.pnbs.gov.cn/web!listItem.action?ivo.showtype=qy&ivo.typeimg=/sp/out/images/itemtypeimg/qy/ztfl/root_qy_ztfl_aqfh.png&ivo.showtypename=%B0%B2%C8%AB%B7%C0%BB%A4&ivo.affairid=WORDBOOK00051633" target="_blank"><img src="${ctx}/resources/web/image/icons/35.png" width="64" height="64" /><br />安全防护</a></li>
<li><a href="http://www.pnbs.gov.cn/web!listItem.action?ivo.showtype=qy&ivo.typeimg=/sp/out/images/itemtypeimg/qy/ztfl/root_qy_ztfl_hblh.png&ivo.showtypename=%BB%B7%B1%A3%C2%CC%BB%AF&ivo.affairid=WORDBOOK00051634" target="_blank"><img src="${ctx}/resources/web/image/icons/36.png" width="64" height="64" /><br />环保绿化</a></li>
<li><a href="http://www.pnbs.gov.cn/web!listItem.action?ivo.showtype=qy&ivo.typeimg=/sp/out/images/itemtypeimg/qy/ztfl/root_qy_ztfl_tdfc.png&ivo.showtypename=%CD%C1%B5%D8%B7%BF%B2%FA&ivo.affairid=WORDBOOK00051635" target="_blank"><img src="${ctx}/resources/web/image/icons/37.png" width="64" height="64" /><br />土地房产</a></li>
<li><a href="http://www.pnbs.gov.cn/web!listItem.action?ivo.showtype=qy&ivo.typeimg=/sp/out/images/itemtypeimg/qy/ztfl/root_qy_ztfl_wwbh.png&ivo.showtypename=%CE%C4%CE%EF%B1%A3%BB%A4&ivo.affairid=WORDBOOK00051636" target="_blank"><img src="${ctx}/resources/web/image/icons/38.png" width="64" height="64" /><br />文物保护</a></li>
<li><a href="http://www.pnbs.gov.cn/web!listItem.action?ivo.showtype=qy&ivo.typeimg=/sp/out/images/itemtypeimg/qy/ztfl/root_qy_ztfl_xwgd.png&ivo.showtypename=%D0%C2%CE%C5%B9%E3%B5%E7&ivo.affairid=WORDBOOK00051637" target="_blank"><img src="${ctx}/resources/web/image/icons/39.png" width="64" height="64" /><br />新闻广电</a></li>
<li><a href="http://www.pnbs.gov.cn/web!listItem.action?ivo.showtype=qy&ivo.typeimg=/sp/out/images/itemtypeimg/qy/ztfl/root_qy_ztfl_jtys.png&ivo.showtypename=%BD%BB%CD%A8%D4%CB%CA%E4&ivo.affairid=WORDBOOK00051638" target="_blank"><img src="${ctx}/resources/web/image/icons/40.png" width="64" height="64" /><br />交通运输</a></li>
<li><a href="http://www.pnbs.gov.cn/web!listItem.action?ivo.showtype=qy&ivo.typeimg=/sp/out/images/itemtypeimg/qy/ztfl/root_qy_ztfl_nlmy.png&ivo.showtypename=%C5%A9%C1%D6%C4%C1%D3%E6&ivo.affairid=WORDBOOK00051639" target="_blank"><img src="${ctx}/resources/web/image/icons/41.png" width="64" height="64" /><br />农林牧渔</a></li>
<li><a href="http://www.pnbs.gov.cn/web!listItem.action?ivo.showtype=qy&ivo.typeimg=/sp/out/images/itemtypeimg/qy/ztfl/root_qy_ztfl_slsw.png&ivo.showtypename=%CB%AE%C0%FB%CB%AE%CE%F1&ivo.affairid=WORDBOOK00051640" target="_blank"><img src="${ctx}/resources/web/image/icons/42.png" width="64" height="64" /><br />水利水务</a></li>
<li><a href="http://www.pnbs.gov.cn/web!listItem.action?ivo.showtype=qy&ivo.typeimg=/sp/out/images/itemtypeimg/qy/ztfl/root_qy_ztfl_ylws.png&ivo.showtypename=%D2%BD%C1%C6%CE%C0%C9%FA&ivo.affairid=WORDBOOK00051641" target="_blank"><img src="${ctx}/resources/web/image/icons/43.png" width="64" height="64" /><br />医疗卫生</a></li>
<li><a href="http://www.pnbs.gov.cn/web!listItem.action?ivo.showtype=qy&ivo.typeimg=/sp/out/images/itemtypeimg/qy/ztfl/root_qy_ztfl_zscq.png&ivo.showtypename=%D6%AA%CA%B6%B2%FA%C8%A8&ivo.affairid=WORDBOOK00051642" target="_blank"><img src="${ctx}/resources/web/image/icons/44.png" width="64" height="64" /><br />知识产权</a></li>
<li><a href="http://www.pnbs.gov.cn/web!listItem.action?ivo.showtype=qy&ivo.typeimg=/sp/out/images/itemtypeimg/qy/ztfl/root_qy_ztfl_pczx.png&ivo.showtypename=%C6%C6%B2%FA%D7%A2%CF%FA&ivo.affairid=WORDBOOK00051643" target="_blank"><img src="${ctx}/resources/web/image/icons/45.png" width="64" height="64" /><br />破产注销</a></li>
<li><a href="http://www.pnbs.gov.cn/web!listItem.action?ivo.showtype=qy&ivo.typeimg=/sp/out/images/itemtypeimg/qy/ztfl/root_qy_ztfl_qt.png&ivo.showtypename=%C6%E4%CB%FB&ivo.affairid=WORDBOOK00051644" target="_blank"><img src="${ctx}/resources/web/image/icons/46.png" width="64" height="64" /><br />其他</a></li>

        </ul>     
        <table cellpadding="0" cellspacing="0" border="0" width="100%" class="hide">
        <tr>                        
<td><a target="_blank" href="http://www.pnbs.gov.cn/web!listItem.action?ivo.showtype=bm&ivo.typeimg=/upload/upfiles/20130122/201301221522430.png&ivo.showtypename=%C6%D5%C4%FE%CA%D0%CD%B3%BC%C6%BE%D6&ivo.orgid=DEPARTMENT00001625">市统计局</a></td>
<td><a target="_blank" href="http://www.pnbs.gov.cn/web!listItem.action?ivo.showtype=bm&ivo.typeimg=/upload/upfiles/20121217/201212171702520.png&ivo.showtypename=%C6%D5%C4%FE%CA%D0%BB%B7%BE%B3%B1%A3%BB%A4%BE%D6&ivo.orgid=DEPARTMENT00001561">市环保局</a></td>
<td><a target="_blank" href="http://www.pnbs.gov.cn/web!listItem.action?ivo.showtype=bm&ivo.typeimg=/upload/upfiles/20141208/201412081159590.png&ivo.showtypename=%C6%D5%C4%FE%CA%D0%B9%FA%BC%D2%B1%A3%C3%DC%BE%D6&ivo.orgid=DEPARTMENT00001885">市保密局</a></td>
<td><a target="_blank" href="http://www.pnbs.gov.cn/web!listItem.action?ivo.showtype=bm&ivo.typeimg=/upload/upfiles/20130122/201301221449270.png&ivo.showtypename=%C6%D5%C4%FE%CA%D0%C3%F1%D7%E5%D7%DA%BD%CC%CA%C2%CE%F1%BE%D6&ivo.orgid=DEPARTMENT00001533">市宗教局</a></td>
<td><a target="_blank" href="http://www.pnbs.gov.cn/web!listItem.action?ivo.showtype=bm&ivo.typeimg=/upload/upfiles/20121217/201212171659350.png&ivo.showtypename=%C6%D5%C4%FE%CA%D0%D0%F3%C4%C1%CB%AE%B2%FA%BE%D6&ivo.orgid=DEPARTMENT00001551">市畜牧水产局</a></td>
        </tr>
        <tr class="trbg">  
<td><a target="_blank" href="http://www.pnbs.gov.cn/web!listItem.action?ivo.showtype=bm&ivo.typeimg=/upload/upfiles/20121217/201212171658500.png&ivo.showtypename=%C6%D5%C4%FE%CA%D0%B9%AB%C2%B7%BE%D6&ivo.orgid=DEPARTMENT00001547">市公路局</a></td>					
<td><a target="_blank" href="http://www.pnbs.gov.cn/web!listItem.action?ivo.showtype=bm&ivo.typeimg=/upload/upfiles/20121217/201212171659100.png&ivo.showtypename=%C6%D5%C4%FE%CA%D0%B5%B5%B0%B8%BE%D6&ivo.orgid=DEPARTMENT00001549">市档案局</a></td>
<td><a target="_blank" href="http://www.pnbs.gov.cn/web!listItem.action?ivo.showtype=bm&ivo.typeimg=/upload/upfiles/20121218/201212180854180.png&ivo.showtypename=%C6%D5%C4%FE%CA%D0%B0%B2%C8%AB%C9%FA%B2%FA%BC%E0%B6%BD%B9%DC%C0%ED%BE%D6&ivo.orgid=DEPARTMENT00001599">市安监局</a></td>
<td><a target="_blank" href="http://www.pnbs.gov.cn/web!listItem.action?ivo.showtype=bm&ivo.typeimg=/upload/upfiles/20121210/201212100944110.png&ivo.showtypename=%C6%D5%C4%FE%CA%D0%C6%F8%CF%F3%BE%D6&ivo.orgid=DEPARTMENT00001541">市气象局</a></td>
<td><a target="_blank" href="http://www.pnbs.gov.cn/web!listItem.action?ivo.showtype=bm&ivo.typeimg=/upload/upfiles/20121217/201212171700430.png&ivo.showtypename=%C6%D5%C4%FE%CA%D0%B2%C6%D5%FE%BE%D6&ivo.orgid=DEPARTMENT00001555">市财政局</a></td>
        </tr>
        <tr>   
<td><a target="_blank" href="http://www.pnbs.gov.cn/web!listItem.action?ivo.showtype=bm&ivo.typeimg=/upload/upfiles/20121217/201212171708510.png&ivo.showtypename=%C6%D5%C4%FE%CA%D0%BB%FA%B9%B9%B1%E0%D6%C6%CE%AF%D4%B1%BB%E1%B0%EC%B9%AB%CA%D2&ivo.orgid=DEPARTMENT00001617">市编办</a></td>
<td><a target="_blank" href="http://www.pnbs.gov.cn/web!listItem.action?ivo.showtype=bm&ivo.typeimg=/upload/upfiles/20121210/201212101100170.png&ivo.showtypename=%C6%D5%C4%FE%CA%D0%B9%FA%D3%D0%D7%CA%B2%FA%B9%DC%C0%ED%BE%D6&ivo.orgid=DEPARTMENT00001539">市国资局</a></td>                         
<td><a target="_blank" href="http://www.pnbs.gov.cn/web!listItem.action?ivo.showtype=bm&ivo.typeimg=/upload/upfiles/20121217/201212171707370.png&ivo.showtypename=%C6%D5%C4%FE%CA%D0%C3%F1%D5%FE%BE%D6&ivo.orgid=DEPARTMENT00001621">市民政局</a></td>
<td><a target="_blank" href="http://www.pnbs.gov.cn/web!listItem.action?ivo.showtype=bm&ivo.typeimg=/upload/upfiles/20121210/201212101005330.png&ivo.showtypename=%C6%D5%C4%FE%CA%D0%CC%E5%D3%FD%BE%D6&ivo.orgid=DEPARTMENT00001592">市体育局</a></td>
<td><a target="_blank" href="http://www.pnbs.gov.cn/web!listItem.action?ivo.showtype=bm&ivo.typeimg=/upload/upfiles/20121218/201212180858250.png&ivo.showtypename=%C6%D5%C4%FE%CA%D0%B9%E3%B2%A5%B5%E7%CA%D3%CC%A8&ivo.orgid=DEPARTMENT00001633">市电视台</a></td>
        </tr>
        <tr class="trbg"> 
<td><a target="_blank" href="http://www.pnbs.gov.cn/web!listItem.action?ivo.showtype=bm&ivo.typeimg=/upload/upfiles/20141208/201412081007410.png&ivo.showtypename=%C6%D5%C4%FE%CA%D0%D7%A1%B7%BF%BA%CD%B3%C7%CF%E7%BD%A8%C9%E8%BE%D6&ivo.orgid=DEPARTMENT00001878">市住建局</a></td>
<td><a target="_blank" href="http://www.pnbs.gov.cn/web!listItem.action?ivo.showtype=bm&ivo.typeimg=/upload/upfiles/20121218/201212180856030.png&ivo.showtypename=%C6%D5%C4%FE%CA%D0%CB%AE%CE%F1%BE%D6&ivo.orgid=DEPARTMENT00001585">市水务局</a></td>
<td><a target="_blank" href="http://www.pnbs.gov.cn/web!listItem.action?ivo.showtype=bm&ivo.typeimg=/upload/upfiles/20121217/201212171708100.png&ivo.showtypename=%C6%D5%C4%FE%CA%D0%CB%BE%B7%A8%BE%D6&ivo.orgid=DEPARTMENT00001619">市司法局</a></td>                             
<td><a target="_blank" href="http://www.pnbs.gov.cn/web!listItem.action?ivo.showtype=bm&ivo.typeimg=/upload/upfiles/20121218/201212180853460.png&ivo.showtypename=%C6%D5%C4%FE%CA%D0%B9%FA%CD%C1%D7%CA%D4%B4%BE%D6&ivo.orgid=DEPARTMENT00001601">市国土局</a></td>
<td><a target="_blank" href="http://www.pnbs.gov.cn/web!listItem.action?ivo.showtype=bm&ivo.typeimg=/upload/upfiles/20121217/201212171705450.png&ivo.showtypename=%C6%D5%C4%FE%CA%D0%CD%E2%CA%C2%C7%C8%CE%F1%BE%D6&ivo.orgid=DEPARTMENT00001623">市外事侨务局</a></td>
        </tr>
        <tr>
<td><a target="_blank" href="http://www.pnbs.gov.cn/web!listItem.action?ivo.showtype=bm&ivo.typeimg=/upload/upfiles/20121218/201212180851390.png&ivo.showtypename=%C6%D5%C4%FE%CA%D0%CA%B3%C6%B7%D2%A9%C6%B7%BC%E0%B6%BD%B9%DC%C0%ED%BE%D6&ivo.orgid=DEPARTMENT00001611">市食药品监督局</a></td>
<td><a target="_blank" href="http://www.pnbs.gov.cn/web!listItem.action?ivo.showtype=bm&ivo.typeimg=/upload/upfiles/20141208/201412081042110.png&ivo.showtypename=%C6%D5%C4%FE%CA%D0%B3%C7%CA%D0%B9%DC%C0%ED%BE%D6&ivo.orgid=DEPARTMENT00001881">市城管局</a></td>
<td><a target="_blank" href="http://www.pnbs.gov.cn/web!listItem.action?ivo.showtype=bm&ivo.typeimg=/upload/upfiles/20121217/201212171710410.png&ivo.showtypename=%C6%D5%C4%FE%CA%D0%BD%BB%CD%A8%D4%CB%CA%E4%BE%D6&ivo.orgid=DEPARTMENT00001613">市交通局</a></td>
<td><a target="_blank" href="http://www.pnbs.gov.cn/web!listItem.action?ivo.showtype=bm&ivo.typeimg=/upload/upfiles/20141208/201412081056180.png&ivo.showtypename=%C6%D5%C4%FE%CA%D0%B7%A2%D5%B9%BA%CD%B8%C4%B8%EF%BE%D6&ivo.orgid=DEPARTMENT00001873">市发改局</a></td>			                            
<td><a target="_blank" href="http://www.pnbs.gov.cn/web!listItem.action?ivo.showtype=bm&ivo.typeimg=/upload/upfiles/20121218/201212180855050.png&ivo.showtypename=%C6%D5%C4%FE%CA%D0%BE%AD%BC%C3%BA%CD%D0%C5%CF%A2%BB%AF%BE%D6&ivo.orgid=DEPARTMENT00001595">市经信局</a></td>
        </tr>
        <tr class="trbg">  
<td><a target="_blank" href="http://www.pnbs.gov.cn/web!listItem.action?ivo.showtype=bm&ivo.typeimg=/upload/upfiles/20121217/201212171705140.png&ivo.showtypename=%C6%D5%C4%FE%CA%D0%C2%C3%D3%CE%BE%D6&ivo.orgid=DEPARTMENT00001589">市旅游局</a></td>
<td><a target="_blank" href="http://www.pnbs.gov.cn/web!listItem.action?ivo.showtype=bm&ivo.typeimg=/upload/upfiles/20130122/201301221511190.png&ivo.showtypename=%C6%D5%C4%FE%CA%D0%D1%CE%CE%F1%BE%D6&ivo.orgid=DEPARTMENT00001535">市盐务局</a></td>
<td><a target="_blank" href="http://www.pnbs.gov.cn/web!listItem.action?ivo.showtype=bm&ivo.typeimg=/upload/upfiles/20121217/201212171701450.png&ivo.showtypename=%C6%D5%C4%FE%CA%D0%C1%D6%D2%B5%BE%D6&ivo.orgid=DEPARTMENT00001557">市林业局</a></td>
<td><a target="_blank" href="http://www.pnbs.gov.cn/web!listItem.action?ivo.showtype=bm&ivo.typeimg=/upload/upfiles/20121217/201212171711330.png&ivo.showtypename=%C6%D5%C4%FE%CA%D0%B5%D8%B7%BD%CB%B0%CE%F1%BE%D6&ivo.orgid=DEPARTMENT00001609">市地税局</a></td>
<td><a target="_blank" href="http://www.pnbs.gov.cn/web!listItem.action?ivo.showtype=bm&ivo.typeimg=/upload/upfiles/20121218/201212180856230.png&ivo.showtypename=%C6%D5%C4%FE%CA%D0%B9%AB%B0%B2%BE%D6&ivo.orgid=DEPARTMENT00001581">市公安局</a></td>			
        </tr>
        <tr>                              
<td><a target="_blank" href="http://www.pnbs.gov.cn/web!listItem.action?ivo.showtype=bm&ivo.typeimg=/upload/upfiles/20121217/201212171656380.png&ivo.showtypename=%C6%D5%C4%FE%CA%D0%C8%CB%C3%F1%B7%C0%BF%D5%B0%EC%B9%AB%CA%D2&ivo.orgid=DEPARTMENT00001530">市人防办</a></td>
<td><a target="_blank" href="http://www.pnbs.gov.cn/web!listItem.action?ivo.showtype=bm&ivo.typeimg=/upload/upfiles/20121217/201212171712020.png&ivo.showtypename=%C6%D5%C4%FE%CA%D0%CE%C4%BB%AF%B9%E3%B2%A5%D0%C2%CE%C5%B3%F6%B0%E6%BE%D6&ivo.orgid=DEPARTMENT00001607">市文广新局</a></td>
<td><a target="_blank" href="http://www.pnbs.gov.cn/web!listItem.action?ivo.showtype=bm&ivo.typeimg=/upload/upfiles/20121218/201212180901140.png&ivo.showtypename=%C6%D5%C4%FE%CA%D0%C5%A9%D2%B5%BE%D6&ivo.orgid=DEPARTMENT00001591">市农业局</a></td>
<td><a target="_blank" href="http://www.pnbs.gov.cn/web!listItem.action?ivo.showtype=bm&ivo.typeimg=/upload/upfiles/20121218/201212180856460.png&ivo.showtypename=%C6%D5%C4%FE%CA%D0%C8%CB%C1%A6%D7%CA%D4%B4%BA%CD%C9%E7%BB%E1%B1%A3%D5%CF%BE%D6&ivo.orgid=DEPARTMENT00001576">市人社局</a></td>
<td><a target="_blank" href="http://www.pnbs.gov.cn/web!listItem.action?ivo.showtype=bm&ivo.typeimg=/upload/upfiles/20121218/201212180857050.png&ivo.showtypename=%C6%D5%C4%FE%CA%D0%B7%BF%B5%D8%B2%FA%B9%DC%C0%ED%BE%D6&ivo.orgid=DEPARTMENT00001567">市房产局</a></td>
        </tr>  
        <tr class="trbg">   
<td><a target="_blank" href="http://www.pnbs.gov.cn/web!listItem.action?ivo.showtype=bm&ivo.typeimg=/upload/upfiles/20141208/201412081101000.png&ivo.showtypename=%C6%D5%C4%FE%CA%D0%CA%D0%B3%A1%BC%E0%B6%BD%B9%DC%C0%ED%BE%D6&ivo.orgid=DEPARTMENT00001883">市市场监督局</a></td>                         
<td><a target="_blank" href="http://www.pnbs.gov.cn/web!listItem.action?ivo.showtype=bm&ivo.typeimg=/upload/upfiles/20121218/201212180857570.png&ivo.showtypename=%C6%D5%C4%FE%CA%D0%B9%A9%B5%E7%BE%D6&ivo.orgid=DEPARTMENT00001629">市供电局</a></td>
<td><a target="_blank" href="http://www.pnbs.gov.cn/web!listItem.action?ivo.showtype=bm&ivo.typeimg=/upload/upfiles/20121217/201212171658160.png&ivo.showtypename=%C6%D5%C4%FE%CA%D0%B2%D0%BC%B2%C8%CB%C1%AA%BA%CF%BB%E1&ivo.orgid=DEPARTMENT00001545">市残联</a></td>
<td><a target="_blank" href="http://www.pnbs.gov.cn/web!listItem.action?ivo.showtype=bm&ivo.typeimg=/upload/upfiles/20121217/201212171655330.png&ivo.showtypename=%C6%D5%C4%FE%CA%D0%B9%FA%CB%B0%BE%D6&ivo.orgid=DEPARTMENT00001527">市国税局</a></td>
<td><a target="_blank" href="http://www.pnbs.gov.cn/web!listItem.action?ivo.showtype=bm&ivo.typeimg=/upload/upfiles/20121217/201212171709350.png&ivo.showtypename=%C6%D5%C4%FE%CA%D0%BD%CC%D3%FD%BE%D6&ivo.orgid=DEPARTMENT00001615">市教育局</a></td>
        </tr>   
        <tr> 
<td><a target="_blank" href="http://www.pnbs.gov.cn/web!listItem.action?ivo.showtype=bm&ivo.typeimg=/upload/upfiles/20121218/201212180855280.png&ivo.showtypename=%C6%D5%C4%FE%CA%D0%B9%A9%CB%AE%BE%D6&ivo.orgid=DEPARTMENT00001587">市供水局</a></td>
<td><a target="_blank" href="http://www.pnbs.gov.cn/web!listItem.action?ivo.showtype=bm&ivo.typeimg=/upload/upfiles/20121217/201212171704200.png&ivo.showtypename=%C6%D5%C4%FE%CA%D0%BF%C6%D1%A7%BC%BC%CA%F5%BE%D6&ivo.orgid=DEPARTMENT00001578">市科技局</a></td>			                             
<td><a target="_blank" href="http://www.pnbs.gov.cn/web!listItem.action?ivo.showtype=bm&ivo.typeimg=/upload/upfiles/20141208/201412080907420.png&ivo.showtypename=%C6%D5%C4%FE%CA%D0%CE%C0%C9%FA%BA%CD%BC%C6%BB%AE%C9%FA%D3%FD%BE%D6&ivo.orgid=DEPARTMENT00001875">市卫计局</a></td>
<td><a target="_blank" href="http://www.pnbs.gov.cn/web!listItem.action?ivo.showtype=bm&ivo.typeimg=/upload/upfiles/20130819/201308191550370.png&ivo.showtypename=%C6%D5%C4%FE%CA%D0%B7%C0%C0%D7%C9%E8%CA%A9%BC%EC%B2%E2%CB%F9&ivo.orgid=DEPARTMENT00001777">市防雷所</a></td>
<td><a target="_blank" href="http://www.pnbs.gov.cn/web!listItem.action?ivo.showtype=bm&ivo.typeimg=/upload/upfiles/20121218/201212180852290.png&ivo.showtypename=%C6%D5%C4%FE%CA%D0%B9%AB%B0%B2%CF%FB%B7%C0%B4%F3%B6%D3&ivo.orgid=DEPARTMENT00001605">市公安消防大队</a></td>
        </tr> 
        </table>
                   
    </div>
</div>
